# Generated by Django 3.1.2 on 2021-05-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordGenearator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('site_name', models.CharField(max_length=50)),
                ('length', models.CharField(max_length=10000)),
                ('No_of_password', models.CharField(max_length=4000)),
            ],
        ),
    ]
